apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ include "policy-service.namespace" . }}
  labels:
    {{- include "policy-service.labels" . | nindent 4 }}
data:
  DATABASE_URL: {{ .Values.configMap.data.DATABASE_URL | quote }}
  SECRET_KEY: {{ .Values.configMap.data.SECRET_KEY | quote }}
  ALGORITHM: {{ .Values.configMap.data.ALGORITHM | quote }}
