apiVersion: v1
kind: Secret
metadata:
  name: frontend-secret
  namespace: insurance
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: insurance-platform
type: Opaque
stringData:
  REACT_APP_API_TOKEN: change-me-if-needed
