apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: insurance
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: insurance-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: frontend
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
