apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ include "api-gateway.namespace" . }}
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
data:
  USER_SERVICE_URL: {{ .Values.configMap.data.USER_SERVICE_URL | quote }}
  POLICY_SERVICE_URL: {{ .Values.configMap.data.POLICY_SERVICE_URL | quote }}
  CLAIMS_SERVICE_URL: {{ .Values.configMap.data.CLAIMS_SERVICE_URL | quote }}
  PAYMENT_SERVICE_URL: {{ .Values.configMap.data.PAYMENT_SERVICE_URL | quote }}
  SECRET_KEY: {{ .Values.configMap.data.SECRET_KEY | quote }}
  ALGORITHM: {{ .Values.configMap.data.ALGORITHM | quote }}
