apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "api-gateway.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ .Values.namespace.labels.name }}
    app.kubernetes.io/part-of: {{ .Values.global.partOf }}
