apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: insurance
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: insurance-platform
spec:
  serviceName: mysql-headless
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mysql
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: insurance-platform
    spec:
      restartPolicy: Always
      containers:
        - name: mysql
          image: mysql:8.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
              name: mysql
              protocol: TCP
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: change-me
            - name: MYSQL_DATABASE
              value: insurance_db
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: mysql-init-sql
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
              readOnly: true
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -h 127.0.0.1 -uroot -p$MYSQL_ROOT_PASSWORD
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -h 127.0.0.1 -uroot -p$MYSQL_ROOT_PASSWORD
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 6
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
      volumes:
        - name: mysql-init-sql
          configMap:
            name: mysql-init-sql
            items:
              - key: init.sql
                path: init.sql
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
        labels:
          app.kubernetes.io/name: mysql
          app.kubernetes.io/component: database
          app.kubernetes.io/part-of: insurance-platform
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: mysql-retain-sc
        resources:
          requests:
            storage: 5Gi
