apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: insurance
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: insurance-platform
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: change-me
  MYSQL_DATABASE: insurance_db
