apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ include "mysql.namespace" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
data:
  init.sql: |
{{ .Values.configMap.initSql | nindent 4 }}
