apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: insurance
  labels:
    app.kubernetes.io/name: user-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: insurance-platform
data:
  DATABASE_URL: mysql+pymysql://root:change-me@mysql:3306/insurance_db
  SECRET_KEY: change-me-in-production
  ALGORITHM: HS256
  ACCESS_TOKEN_EXPIRE_MINUTES: "60"
