apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: insurance
  labels:
    app.kubernetes.io/name: user-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: insurance-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: user-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: user-service
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: insurance-platform
    spec:
      restartPolicy: Always
      containers:
        - name: user-service
          image: kajapathy/user-service:v1.1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
              name: http
              protocol: TCP
          envFrom:
            - configMapRef:
                name: user-service-config
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: 150m
              memory: 192Mi
            limits:
              cpu: 700m
              memory: 768Mi
