apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: insurance
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: insurance-platform
data:
  USER_SERVICE_URL: http://user-service:8001
  POLICY_SERVICE_URL: http://policy-service:8002
  CLAIMS_SERVICE_URL: http://claims-service:8003
  PAYMENT_SERVICE_URL: http://payment-service:8004
  SECRET_KEY: change-me-in-production
  ALGORITHM: HS256
