apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ include "user-service.namespace" . }}
  labels:
    {{- include "user-service.labels" . | nindent 4 }}
data:
  DATABASE_URL: {{ .Values.configMap.data.DATABASE_URL | quote }}
  SECRET_KEY: {{ .Values.configMap.data.SECRET_KEY | quote }}
  ALGORITHM: {{ .Values.configMap.data.ALGORITHM | quote }}
  ACCESS_TOKEN_EXPIRE_MINUTES: {{ .Values.configMap.data.ACCESS_TOKEN_EXPIRE_MINUTES | quote }}
