apiVersion: v1
kind: Secret
metadata:
  name: policy-service-secret
  namespace: insurance
  labels:
    app.kubernetes.io/name: policy-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: insurance-platform
type: Opaque
stringData:
  DATABASE_URL: mysql+pymysql://root:change-me@mysql:3306/insurance_db
  SECRET_KEY: change-me-in-production
