apiVersion: v1
kind: Service
metadata:
  name: policy-service
  namespace: insurance
  labels:
    app.kubernetes.io/name: policy-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: insurance-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: policy-service
  ports:
    - name: http
      port: 8002
      targetPort: http
      protocol: TCP
