namespace:
  name: insurance-prod

fullnameOverride: ""

app:
  name: frontend

global:
  component: frontend
  partOf: insurance-platform

serviceAccount:
  create: false
  name: ""

replicaCount: 1

image:
  repository: kajapathy/frontend
  tag: v1.1.3
  pullPolicy: Always

container:
  name: frontend
  portName: http
  port: 8080

service:
  name: frontend
  type: ClusterIP
  portName: http
  port: 3000
  targetPort: http
  protocol: TCP

configMap:
  name: frontend-config
  data:
    REACT_APP_API_URL: http://api-gateway:8000

readinessProbe:
  path: /health
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3

livenessProbe:
  path: /health
  initialDelaySeconds: 20
  periodSeconds: 20
  timeoutSeconds: 3
  failureThreshold: 3

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 300m
    memory: 256Mi
